#spring:
#  banner:
#    charset: UTF-8 # Banner file encoding.
#    location: classpath:mapper/banner.txt # Banner file location.
#    image:
#      location: classpath:banner.jpg # Banner image file location (jpg/png can also be used).
#      width: 70 # Width of the banner image in chars (default 76)
#      height: 22 # Height of the banner image in chars (default based on image height)
#      margin: -1 # Left hand image margin in chars (default 2)
#      invert: false # If images should be inverted for dark terminal themes (default false)
#      AnsibBackground: blue
