server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.77.176:1111 #Nacos服务注册中心地址
    sentinel:
      transport:
#        dashboard: 124.221.77.176:9999 #配置Sentinel dashboard地址
        dashboard: localhost:9999 #配置Sentinel dashboard地址
        port: 8719
      datasource: #<---------------------------关注点，添加Nacos数据源配置 持久化
        ds1:
          nacos:
            server-addr: 124.221.77.176:1111
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

