server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.77.176:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
