server:
  port: 88


spring:
  gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://qq.com
          predicates:
            - Query=url,qq
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.77.176:1111
